nombre = 'Alessandra'

print(nombre[0])
nombres = ["Alessandra", "Hector", "Balam", "Paulina", "Raul", "Jocelyn"]
print(nombres)


nombres[0] = 'Alessandra'
print(nombres) 
           

coordenadaX = 10
coordenadaY = 5.3
coordenadas = (coordenadaX, coordenadaY)

print(coordenadas)
coordenadas[0]=34
print(coordenadas)


#Listas (arreglos) - Una secuencia de variables mutables
#Tuplas - Secuencia ()
